name: Run Python Script Every Hour with Env Variables

on:
  schedule:
    # Rodar a cada hora
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checar o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Adicionar variáveis de ambiente a partir dos secrets
      - name: Setup environment variables
        run: |
          echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      # Instalar dependências, se houver
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Instalar dotenv
      - name: Install dotenv
        run: pip install python-dotenv

      # Rodar o script Python
      - name: Run script
        run: python main.py
