name: Run Python Script Every Hour

on:
  schedule:
    # Rodar a cada hora
    - cron: '0 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checar o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar o Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      # Instalar dependências, se houver
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Rodar o script Python
      - name: Run script
        run: python main.py
